### ISSUE TITLE
Version 1.0.4 Deployment Fails on PS Module GR-Utilities

### ISSUE THREAD

**Issue by Rioux1010** [Azure/GuardrailsSolutionAccelerator#158]
**Describe the bug**

Version 1.0.4 Deployment Fails on PS Module GR-Utilities

**To Reproduce**

On Version 1.0.4, go to file : ./setup/guardrails.bicep  

line 18
`param CustomModulesBaseURL string = 'https://github.com/Azure/GuardrailsSolutionAccelerator/raw/main/psmodules'`

line 979
`uri: '${CustomModulesBaseURL}/GR-Utilities.zip'`

Zip does not exist : https://github.com/Azure/GuardrailsSolutionAccelerator/raw/main/psmodules/GR-Utilities.zip 

**Expected behavior**
Zip exist or GR-Common is renamed to GR-Utilities.zip

**Comment by igomaa** [comment]
hello @Rioux1010  ,
this issue is cause by renaming the GR-utilities.zip to GR-Common.zip , 
in version 1.05 that issue will be resolved, mean time, can you please deploy by cloning the solution
Git clone https://github.com/Azure/GuardrailsSolutionAccelerator

**Comment by Rioux1010** [comment]
> 

FYI. If we clone the solution it gives multiple module failure on deployment :

![image](https://user-images.githubusercontent.com/114452616/193043015-5a3afa2a-6557-456f-a54a-a7630a9ab96e.png)

What i end up doing is install the vesion 1.0.4 and manually downloaded and installed the GR-Utilities.zip module in the Automation Account

**Comment by igomaa** [comment]
this is because you had deleted the solution and redeploy it again, the issue mainly in the Log analytics workspace and the soft delete, that preserve the data.  until we finalize the cleanup process, please run the following cmdlets 
* Remove-AzOperationalInsightsWorkspace -ResourceGroupName Guardrails-0000000000 -Name Guardrails-0000000000  -ForceDelete
* Remove-AzResourceGroup -Name Guardrails-0000000000 -force
 
Thanks
