### ISSUE TITLE
Workbook not showing results even though data is present in the log analytics

### ISSUE THREAD

**Issue by precog90** [Azure/GuardrailsSolutionAccelerator#314]
**Describe the bug**
Even though log analytics workspace has compliance data, Workbook for some guardrails says "The query returned no results."

**Expected behavior**
If compliance data is present in the log analytics, Azure workbook displays the results accurately

**Screenshots**
![image](https://user-images.githubusercontent.com/8752276/219086825-25417db8-efd6-4af3-8154-59bddd958a0b.png)
![image](https://user-images.githubusercontent.com/8752276/219087434-85101226-4f7c-4440-bfac-6453553ca6c4.png)
![image](https://user-images.githubusercontent.com/8752276/219087712-70b177b1-6c6e-44c0-87b9-a58a8aad0d04.png)

GRITSGControls_CL has 923 rows:
![image](https://user-images.githubusercontent.com/8752276/219087290-b960254c-cdcf-4c29-ad6d-b7edc8434380.png)

But in workbook queries for a custom table itsgcodes, which is joined to log table has fewer rows due to different time generated entries

itsgcodes has 173 rows as checks only max timegenerated entry but table has two entries for TimeGenerated  time:

![image](https://user-images.githubusercontent.com/8752276/219088585-40c9248a-2e09-48fa-a81a-5d6045a0f1ae.png)

![image](https://user-images.githubusercontent.com/8752276/219088811-3b798e56-da6e-424b-a356-b78fe0645dbe.png)

**Additional context**

In the Azure Workbook, due to loading time of data in the GRITSGControls_CL - I believe
"
let itsgcodes = GRITSGControls_CL | where TimeGenerated == toscalar( GRITSGControls_CL | summarize max(TimeGenerated));
"
This logic needs to be fixed across all the guardrails it is being used.

**Comment by mbrat2005** [comment]
@precog90 I'm not able to reproduce this in testing. In our code that imports the ITSG data to Log Analytics, we specify the value of the TimeGenerated column in the GRITSGControls_CL table, so different values so close together would seem to indicate that the Backend runbook was either executing multiple jobs simultaneously, either due to a transient issue with Azure Automation or duplicate scheduled executions. I suspect that the query was run while the ITSG data was still be ingested, giving partial results (as perhaps you are suggesting). 

A couple workarounds to this situation: 
- use the previous most recent ITSG data, which would be fully ingested 
- change the join type between the ITSG data table and the GuardrailsCompliance table to an outer join, allowing blank values in the ITSG control definition column

@josefehse - thoughts?

**Comment by mbrat2005** [comment]
Using the second most recent ITSG data, or the most recent if there is only one:

```kusto
let itsgcodes=GRITSGControls_CL
    | where TimeGenerated == 
        toscalar(GRITSGControls_CL
        | summarize by TimeGenerated
        | top 2 by TimeGenerated desc
        | top 1 by TimeGenerated asc
        | project TimeGenerated);
```
