### ISSUE TITLE
v1.1.0: Error during deployment

### ISSUE THREAD

**Issue by precog90** [Azure/GuardrailsSolutionAccelerator#333]
**Describe the bug**
Deployment fails with error:
![MicrosoftTeams-image](https://user-images.githubusercontent.com/8752276/223534563-ceb47154-58eb-4eef-8156-29186bf95b8b.png)

![image](https://user-images.githubusercontent.com/8752276/223535217-a9a99d8d-a40b-42d2-892d-248c8d428a7b.png)

**To Reproduce**
Install version v1.1.0

**Additional context**
** We tried to install the solution 3 times with similar error towards the end of the depolyment

Error message in text form:
statusMessage  : {"status":"Failed","error":{"code":"ResourceDeploymentFailure","message":"The 'AzureAsyncOperationWaiting' resource operation 
completed with terminal provisioning state 'Failed'.","details":[{"code":"DeploymentFailed","message":"At least one resource deployment operation failed. Please list 
deployment operations for details. Please see https://aka.ms/arm-deployment-operations for usage details.","details":[{"code":"Conflict","message":"{\r\n  \"status\":
\"Failed\",\r\n  \"error\": {\r\n    \"code\": \"ResourceDeploymentFailure\",\r\n    \"message\": \"The 'Waiting' resource operation completed with terminal provisio
ning state 'Failed'.\"\r\n  }\r\n}"},{"code":"Conflict","message":"{\r\n  \"status\": \"Failed\",\r\n  \"error\": {\r\n    \"code\": \"ResourceDeploymentFailure\",\r\
n    \"message\": \"The 'Waiting' resource operation completed with terminal provisioning state 'Failed'.\"\r\n  }\r\n}"},{"code":"Conflict","message":"{\r\n  \"statu
s\": \"Failed\",\r\n  \"error\": {\r\n    \"code\": \"ResourceDeploymentFailure\",\r\n    \"message\": \"The 'Waiting' resource operation completed with terminal prov
isioning state 'Failed'.\"\r\n  }\r\n}"}]}]}}

**Comment by mbrat2005** [comment]
This setup issue is due to two factors:
- PS module download URLs referencing tags and repo content, rather than releases. The repo did not have updated zips, as we had expected to move to releases only. The URL formatting was a bug.
- Download Github release assets sometimes uses an HTTP redirect, depending on content cache status, which Azure 
Automation does not support. See: https://docs.github.com/en/rest/releases/assets?apiVersion=2022-11-28#:~:text=The%20API%20will%20either%20redirect%20the%20client%20to%20the%20location%2C%20or%20stream%20it%20directly%20if%20possible.%20API%20clients%20should%20handle%20both%20a%20200%20or%20302%20response.

The resolution is to revert to storing the signed and zipped modules directly in the repo code content. This PR refreshed the zip content: https://github.com/Azure/GuardrailsSolutionAccelerator/pull/336

![image](https://user-images.githubusercontent.com/25390936/223739222-4d69d7e2-f8b8-42d4-bdf9-13a85a8d990c.png)
